version: "3"
services:
  dtw_database:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=dtw_local_dev_password
      - POSTGRES_USER=root
    ports:
      - 5432:5432
    volumes:
      - $HOME/github.com/loicbourgois/downtowhat/database/inner.sh:/docker-entrypoint-initdb.d/01_inner.sh:ro
      - $HOME/github.com/loicbourgois/downtowhat/database/migrations/:/migrations/:ro
      # - $HOME/github.com/loicbourgois/dtw/database/logs.txt:/var/lib/postgresql/logs.txt:rw
      - $HOME/github.com/loicbourgois/downtowhat/database/admin:/admin:ro
      - $HOME/github.com/loicbourgois/downtowhat/generated:/generated:ro
